version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/documentation"
      - "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - "*"
          
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      actions-dependencies:
        patterns:
          - "*"
