openapi: 3.1.0
info:
  title: AAC Team Sec2 - API Docs
  description: This API controls basic lobby functionality of the AAC game
paths:
  /lobby:
    post:
      summary: Create Lobby
      description: Creates a new lobby and player, returning lobby information and new player information.
      operationId: lobby_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    $ref: '#/components/schemas/User1'
                  lobby:
                    $ref: '#/components/schemas/Lobby1'

  /lobby/{code}:
    post:
      summary: Join Lobby
      description: Joins a player to a lobby by its unique game code, returning lobby information and new player information.
      operationId: lobby_code_post
      parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
          title: Code
          description: Lobby Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    $ref: '#/components/schemas/User2'
                  lobby:
                    $ref: '#/components/schemas/Lobby2'
        '404':
          description: Lobby Not Found
  /ws/:
    get:
      summary: Websocket Connection
      description: Handles a WebSocket connection for receiving and responding to messages.
components:
  schemas:
    Lobby1:
      type: object
      properties:
        code:
          type: string
          example: Fish-Turtle-Shark
        players:
          type: array
          items:
            $ref: '#/components/schemas/User1'
    Lobby2:
      type: object
      properties:
        code:
          type: string
          example: Fish-Turtle-Shark
        players:
          type: array
          items:
            - $ref: '#/components/schemas/User1'
            - $ref: '#/components/schemas/User2'
    User1:
      type: object
      properties:
        avatar:
          type: string
          example: Fish
        uuid:
          type: string
          example: 3e6b52bf-23ae-4f50-ba84-ad35ed1df31b
    User2:
      type: object
      properties:
        avatar:
          type: string
          example: Shark
        uuid:
          type: string
          example: c2002008-c0b2-4753-8ee5-14effb2f5fa7
