---
name: Update Websocket Schema

on:
  pull_request:
    paths:
      - "backend/models.py"

permissions:
  contents: write

jobs:
  update-schema:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a  # v4.2.0
        with:
          version: "0.5.4"

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Output json schema
        run: uv run backend/models.py > wss_schema.json

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
        with:
          name: wss-schema
          path: wss_schema.json
          overwrite: true
